/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.marketplace.ui.components;

/**
 *
 * @author DELL
 */
public class AccountCard extends javax.swing.JPanel {

    /**
     * Creates new form AccountSection
     */
    public AccountCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeaderBg = new javax.swing.JPanel();
        headerImage = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        panelHello = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Balance = new javax.swing.JLabel();
        panelButtonWrapper = new javax.swing.JPanel();
        TopUp = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        setPreferredSize(new java.awt.Dimension(400, 450));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelHeaderBg.setMaximumSize(new java.awt.Dimension(400, 100));
        panelHeaderBg.setMinimumSize(new java.awt.Dimension(400, 250));
        panelHeaderBg.setPreferredSize(new java.awt.Dimension(400, 150));
        panelHeaderBg.setLayout(new javax.swing.BoxLayout(panelHeaderBg, javax.swing.BoxLayout.LINE_AXIS));

        headerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pbo/marketplace/assets/bg.jpg"))); // NOI18N
        headerImage.setPreferredSize(new java.awt.Dimension(400, 250));
        panelHeaderBg.add(headerImage);

        add(panelHeaderBg);

        panelMain.setPreferredSize(new java.awt.Dimension(400, 200));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] { 200 };
        panelMain.setLayout(jPanel1Layout);

        panelHello.setFont(new java.awt.Font("Liberation Sans", 1, 21)); // NOI18N
        panelHello.setText("Welcome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelMain.add(panelHello, gridBagConstraints);

        Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Name.setText("Rasyid Firmansyah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        panelMain.add(Name, gridBagConstraints);

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setText("rasyidnf.id@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        panelMain.add(Email, gridBagConstraints);

        Balance.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        Balance.setText("Rp 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        panelMain.add(Balance, gridBagConstraints);

        panelButtonWrapper.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        TopUp.setBackground(new java.awt.Color(0, 204, 51));
        TopUp.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        TopUp.setForeground(new java.awt.Color(0, 0, 0));
        TopUp.setText("Top Up");
        TopUp.setPreferredSize(new java.awt.Dimension(300, 35));
        TopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TopUpActionPerformed(evt);
            }
        });
        panelButtonWrapper.add(TopUp);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        panelMain.add(panelButtonWrapper, gridBagConstraints);

        add(panelMain);
    }// </editor-fold>//GEN-END:initComponents

    private void GoToShopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GoToShopActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_GoToShopActionPerformed

    private void TopUpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TopUpActionPerformed

    }// GEN-LAST:event_TopUpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Balance;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Name;
    private javax.swing.JButton TopUp;
    private javax.swing.JLabel headerImage;
    private javax.swing.JPanel panelButtonWrapper;
    private javax.swing.JPanel panelHeaderBg;
    private javax.swing.JLabel panelHello;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
