/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pbo.marketplace;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.pbo.marketplace.ui.sections.CartSection;

import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author rasyid-firmansyah
 */
public class Marketplace extends javax.swing.JFrame {

    /**
     * Creates new form Marketplace
     */
    public Marketplace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNavbar = new javax.swing.JPanel();
        panelButtonNav = new javax.swing.JPanel();
        buttonMyAccount = new javax.swing.JButton();
        buttonMyCart = new javax.swing.JButton();
        panelProgramTitle = new javax.swing.JPanel();
        programTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContainer = new javax.swing.JPanel();
        homeSection1 = new com.pbo.marketplace.ui.sections.HomeSection();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelNavbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 1, true));
        panelNavbar.setPreferredSize(new java.awt.Dimension(1440, 80));
        panelNavbar.setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout panelButtonNavLayout = new java.awt.GridBagLayout();
        panelButtonNavLayout.columnWidths = new int[] { 125 };
        panelButtonNavLayout.columnWeights = new double[] { 30.0 };
        panelButtonNav.setLayout(panelButtonNavLayout);

        buttonMyAccount.setText("My Account");
        buttonMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMyAccountActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 7;
        panelButtonNav.add(buttonMyAccount, gridBagConstraints);

        buttonMyCart.setText("My Cart");
        buttonMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMyCartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelButtonNav.add(buttonMyCart, gridBagConstraints);

        panelNavbar.add(panelButtonNav, java.awt.BorderLayout.EAST);

        panelProgramTitle.setLayout(new java.awt.BorderLayout(10, 0));

        programTitle.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        programTitle.setText("Marketplace");
        panelProgramTitle.add(programTitle, java.awt.BorderLayout.WEST);

        panelNavbar.add(panelProgramTitle, java.awt.BorderLayout.WEST);

        getContentPane().add(panelNavbar);

        int height = homeSection1.getPreferredSize().height;

        panelContainer.setPreferredSize(new java.awt.Dimension(1440, height));
        panelContainer.setLayout(new java.awt.CardLayout());
        panelContainer.add(homeSection1, "card2");

        jScrollPane1.setViewportView(panelContainer);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMyAccountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonMyAccountActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonMyAccountActionPerformed

    private void buttonMyCartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonMyCartActionPerformed
        int height = new CartSection().getPreferredSize().height;
        panelContainer.removeAll();
        panelContainer.setPreferredSize(new java.awt.Dimension(1440, height));
        panelContainer.add(new CartSection());
        panelContainer.revalidate();
        panelContainer.repaint();
    }// GEN-LAST:event_buttonMyCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e.getMessage());
        }

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marketplace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMyAccount;
    private javax.swing.JButton buttonMyCart;
    private com.pbo.marketplace.ui.sections.HomeSection homeSection1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelButtonNav;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelNavbar;
    private javax.swing.JPanel panelProgramTitle;
    private javax.swing.JLabel programTitle;
    // End of variables declaration//GEN-END:variables
}
