/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.marketplace.ui.sections;

import java.util.ArrayList;
import java.util.List;

import com.pbo.marketplace.domain.entities.Cart;
import com.pbo.marketplace.domain.entities.Goods;
import com.pbo.marketplace.domain.entities.User;
import com.pbo.marketplace.retrieve.DatabaseRetrieve;
import com.pbo.marketplace.ui.components.GoodsCheckout;
import com.pbo.marketplace.ui.components.GoodsItem;
import com.pbo.marketplace.writer.DatabaseWriter;

/**
 *
 * @author rasyid-firmansyah
 */
public class CartSection extends javax.swing.JPanel {
        private List<Cart> userCart;

        /**
         * Creates new form CartSection
         */
        public CartSection() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                panelCartNav = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                panelCartMain = new javax.swing.JPanel();
                panelGoodsList = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                panelGoodsWrapper = new javax.swing.JPanel();
                panelPayment = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                panelCheckoutList = new javax.swing.JPanel();
                panelCountWrapper = new javax.swing.JPanel();
                subtotalLabel = new javax.swing.JLabel();
                taxLabel = new javax.swing.JLabel();
                totalLabel = new javax.swing.JLabel();
                subtotal = new javax.swing.JLabel();
                tax = new javax.swing.JLabel();
                total = new javax.swing.JLabel();
                panelButtonWrapper = new javax.swing.JPanel();
                checkoutButton = new javax.swing.JButton();

                setPreferredSize(new java.awt.Dimension(1440, 700));
                setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

                panelCartNav.setPreferredSize(new java.awt.Dimension(1440, 60));
                panelCartNav.setLayout(new java.awt.BorderLayout(10, 0));

                jPanel1.setPreferredSize(new java.awt.Dimension(881, 60));

                jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
                jLabel1.setText("Goods Detail");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 881, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 29, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                panelCartNav.add(jPanel1, java.awt.BorderLayout.WEST);

                jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
                jLabel2.setText("Quantity");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 67, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel2)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 29, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel2)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                panelCartNav.add(jPanel2, java.awt.BorderLayout.CENTER);

                jPanel3.setPreferredSize(new java.awt.Dimension(385, 60));

                jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
                jLabel3.setText("Sub Total");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 385, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel3)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 29, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jLabel3)
                                                                                .addGap(0, 0, Short.MAX_VALUE))));

                panelCartNav.add(jPanel3, java.awt.BorderLayout.EAST);

                add(panelCartNav);

                panelCartMain.setPreferredSize(new java.awt.Dimension(1440, 1380));
                panelCartMain.setLayout(new javax.swing.BoxLayout(panelCartMain, javax.swing.BoxLayout.X_AXIS));

                panelGoodsList.setPreferredSize(new java.awt.Dimension(1080, 478));
                panelGoodsList.setLayout(new java.awt.CardLayout());

                // jScrollPane1.setBorder(null);

                java.awt.GridBagLayout panelGoodsWrapperLayout = new java.awt.GridBagLayout();
                panelGoodsWrapperLayout.columnWidths = new int[] { 1080 };
                panelGoodsWrapper.setLayout(panelGoodsWrapperLayout);

                userCart = new DatabaseRetrieve().JSONParser(Cart.class,
                                "src/main/java/com/pbo/marketplace/database/carts.json");

                if (userCart == null) {
                        userCart = new ArrayList<>();
                }

                for (Cart cart : userCart) {
                        if (cart.getEmail().equals("rasyidnf.id@gmail.com")) {
                                List<Goods> goodsList = cart.getGoodsList();
                                List<Integer> quantity = cart.getQuantity();
                                int gridYPos = 0;

                                for (Goods goods : goodsList) {
                                        String goodsImage = goods.getGoodsPicturePath();
                                        String goodsName = goods.getGoodsName();
                                        String goodsPrice = "Rp " + goods.getGoodsPrice();
                                        String sellerRegion = goods.getSellerRegion();
                                        String goodsRating = goods.getGoodsrating() + "/5.0";
                                        String goodsQuantity = String.valueOf(quantity.get(goodsList.indexOf(goods)));

                                        GoodsItem goodsItem = new GoodsItem(goodsImage, goodsName, goodsPrice,
                                                        sellerRegion, goodsRating, goodsQuantity);
                                        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
                                        gbc.gridx = 0;
                                        gbc.gridy = gridYPos;
                                        gbc.gridwidth = 1; // Ensure it spans only one column
                                        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;
                                        gbc.insets = new java.awt.Insets(10, 0, 10, 0);
                                        panelGoodsWrapper.add(goodsItem, gbc);

                                        gridYPos++;
                                }

                                break;
                        }
                }

                jScrollPane1.setViewportView(panelGoodsWrapper);

                panelGoodsList.add(jScrollPane1, "card2");

                panelCartMain.add(panelGoodsList);

                panelPayment.setPreferredSize(new java.awt.Dimension(360, 478));
                panelPayment.setLayout(new javax.swing.BoxLayout(panelPayment, javax.swing.BoxLayout.Y_AXIS));

                jScrollPane2.setBorder(null);
                jScrollPane2.setPreferredSize(new java.awt.Dimension(360, 450));
                java.awt.GridBagLayout panelCheckoutListLayout = new java.awt.GridBagLayout();
                panelCheckoutList.setLayout(panelCheckoutListLayout);
                java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
                gbc.gridx = 0;
                gbc.gridy = 0;
                gbc.gridwidth = 1;
                gbc.ipady = 30;
                gbc.fill = java.awt.GridBagConstraints.BOTH;
                gbc.insets = new java.awt.Insets(5, 0, 5, 0);

                for (Cart cart : userCart) {
                        if (cart.getEmail().equals("rasyidnf.id@gmail.com")) {
                                List<Goods> goodsList = cart.getGoodsList();
                                int indexGoods = 0;

                                for (Goods goods : goodsList) {
                                        long goodsTotalPrice = cart.getQuantity().get(indexGoods)
                                                        * goods.getGoodsPrice();
                                        String goodsName = goods.getGoodsName();

                                        GoodsCheckout goodsCheckout = new GoodsCheckout(goodsName, goodsTotalPrice,
                                                        cart.getQuantity().get(indexGoods));
                                        panelCheckoutList.add(goodsCheckout, gbc);
                                        gbc.gridy++;
                                        indexGoods++;
                                }

                                break;
                        }
                }

                panelCheckoutList.revalidate();
                panelCheckoutList.repaint();

                jScrollPane2.setViewportView(panelCheckoutList);

                panelPayment.add(jScrollPane2);

                panelCountWrapper.setPreferredSize(new java.awt.Dimension(360, 70));
                java.awt.GridBagLayout panelCountWrapperLayout = new java.awt.GridBagLayout();
                panelCountWrapperLayout.columnWidths = new int[] { 200 };
                panelCountWrapper.setLayout(panelCountWrapperLayout);

                subtotalLabel.setText("Sub Total");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
                panelCountWrapper.add(subtotalLabel, gridBagConstraints);

                taxLabel.setText("Tax");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
                panelCountWrapper.add(taxLabel, gridBagConstraints);

                totalLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
                totalLabel.setText("Total");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
                panelCountWrapper.add(totalLabel, gridBagConstraints);

                subtotal.setText("Rp 0");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridwidth = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                panelCountWrapper.add(subtotal, gridBagConstraints);

                tax.setText("Rp 0");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.gridwidth = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                panelCountWrapper.add(tax, gridBagConstraints);

                total.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
                total.setText("Rp 0");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.gridwidth = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
                panelCountWrapper.add(total, gridBagConstraints);

                for (Cart cart : userCart) {
                        if (cart.getEmail().equals("rasyidnf.id@gmail.com")) {
                                this.subtotal.setText("Rp " + String.valueOf(cart.getSubtotal()));
                                this.tax.setText("Rp " + String.valueOf(cart.getTax()));
                                this.total.setText("Rp " + String.valueOf(cart.getTotal()));
                        }
                }

                panelPayment.add(panelCountWrapper);

                panelButtonWrapper.setPreferredSize(new java.awt.Dimension(360, 40));
                java.awt.GridBagLayout panelButtonWrapperLayout = new java.awt.GridBagLayout();
                panelButtonWrapperLayout.columnWidths = new int[] { 345 };
                panelButtonWrapper.setLayout(panelButtonWrapperLayout);

                checkoutButton.setBackground(new java.awt.Color(0, 153, 255));
                checkoutButton.setForeground(new java.awt.Color(0, 0, 0));
                checkoutButton.setText("Checkout Now");
                checkoutButton.setPreferredSize(new java.awt.Dimension(345, 35));
                checkoutButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                checkoutNowActionPerformed(evt);
                        }
                });

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.ipady = 10;
                panelButtonWrapper.add(checkoutButton, gridBagConstraints);

                panelPayment.add(panelButtonWrapper);

                panelCartMain.add(panelPayment);

                add(panelCartMain);
        }// </editor-fold>//GEN-END:initComponents

        private void checkoutNowActionPerformed(java.awt.event.ActionEvent evt) {
                List<User> userList = new DatabaseRetrieve().JSONParser(User.class,
                                "src/main/java/com/pbo/marketplace/database/users.json");
                List<Cart> cartList = new DatabaseRetrieve().JSONParser(Cart.class,
                                "src/main/java/com/pbo/marketplace/database/carts.json");

                for (User user : userList) {
                        if (user.getEmail().equals("rasyidnf.id@gmail.com")) {
                                for (Cart cart : cartList) {
                                        if (cart.getEmail().equals(user.getEmail())) {
                                                if (user.getBalance() >= cart.getTotal() && cart.getTotal() != 0) {
                                                        userList.set(userList.indexOf(user), new User(user.getEmail(),
                                                                        user.getPassword(), user.getName(),
                                                                        user.getBalance() - cart.getTotal()));

                                                        DatabaseWriter databaseWriter = new DatabaseWriter(userList,
                                                                        "src/main/java/com/pbo/marketplace/database/users.json");
                                                        javax.swing.JOptionPane.showMessageDialog(null,
                                                                        "Checkout is successful");
                                                } else if (cart.getTotal() == 0) {
                                                        javax.swing.JOptionPane.showMessageDialog(null,
                                                                        "You're cart is empty! Please add some goods to your cart first.");
                                                } else {
                                                        javax.swing.JOptionPane.showMessageDialog(null,
                                                                        "You don't have enough money. Please top up your balance first.");
                                                }

                                                break;
                                        }
                                }

                                break;
                        }
                }
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton checkoutButton;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JPanel panelButtonWrapper;
        private javax.swing.JPanel panelCartMain;
        private javax.swing.JPanel panelCartNav;
        private javax.swing.JPanel panelCheckoutList;
        private javax.swing.JPanel panelCountWrapper;
        private javax.swing.JPanel panelGoodsList;
        private javax.swing.JPanel panelGoodsWrapper;
        private javax.swing.JPanel panelPayment;
        private javax.swing.JLabel subtotal;
        private javax.swing.JLabel subtotalLabel;
        private javax.swing.JLabel tax;
        private javax.swing.JLabel taxLabel;
        private javax.swing.JLabel total;
        private javax.swing.JLabel totalLabel;
        // End of variables declaration//GEN-END:variables
}
