/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pbo.marketplace.ui.sections;

import java.util.ArrayList;
import java.util.List;

import com.pbo.marketplace.domain.entities.Goods;
import com.pbo.marketplace.retrieve.DatabaseRetrieve;
import com.pbo.marketplace.ui.components.GoodsCard;

/**
 *
 * @author rasyid-firmansyah
 */
public class HomeSection extends javax.swing.JPanel {
    List<Goods> goodsList = new ArrayList<>();

    /**
     * Creates new form HomeSection
     */
    public HomeSection() {
        initGoodsList();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1440, 1360));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        for (Goods goods : goodsList) {
            String goodsName = goods.getGoodsName();
            String goodsPrice = "Rp " + goods.getGoodsPrice();
            String sellerRegion = goods.getSellerRegion();
            String goodsRating = String.valueOf(goods.getGoodsrating()) + "/5.0";

            goodsCard = new GoodsCard(goodsName, goodsPrice, sellerRegion, goodsRating);
            add(goodsCard);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void initGoodsList() {
        goodsList = new DatabaseRetrieve().JSONParser(Goods.class,
                "src/main/java/com/pbo/marketplace/database/goods.json");

        if (goodsList.isEmpty()) {
            System.out.println("No goods found.");
        } else {
            for (Goods goods : goodsList) {
                System.out.println("Goods Name: " + goods.getGoodsName());
                System.out.println("Goods Price: " + goods.getGoodsPrice());
                System.out.println("Seller Region: " + goods.getSellerRegion());
                System.out.println("Goods Rating: " + goods.getGoodsrating());
                System.out.println();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    GoodsCard goodsCard;
    // End of variables declaration//GEN-END:variables
}
